name: Extraction PE
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x
    - name: List directory contents
      run: |
        ls
    - name: Exec python PE
      env:
         API_KEY: ${{ secrets.API_KEY }}
      run: |
        python PE.py

