name: Extraction PE
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    services:
        mongodb:
            image : mongo:5.0
            container_name: my_mongo
            volumes:
            - ./sample_training:/data/db
            ports:
            - 27017:27017
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
          python-version: 3.x
    - name: Install Python libraries
      run: |
        pip3 install pandas==1.5.3 requests pymongo
    - name: Exec python PE
      env:
         API_PE_KEY: ${{ secrets.API_PE_KEY }}
      run: |
         API_PE_KEY=${{ secrets.API_PE_KEY}} python3 PE.py
